[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.0"
  CI = "false"
  REACT_APP_API_URL = "https://vehicle-auction-system-backend.onrender.com"
  REACT_APP_SUPABASE_URL = "https://qulnppfcpveogwrmcixx.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "t1R0OJymadVIzTFYHImv2S0R5N5zNS9lw"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 